version: '3.4'

services:
  soot-java8:
    container_name: mysoot-java8
    image: soot-java8
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
        - ./app:/usr/app
    ports:
      - 3000:3000

    command: bash -c "javac Hello.java && java Hello" # run java file 
    # command: tail -f /dev/null # keep open container 
    # command: bash -c "javac Hello.java" to generate only the bytecode
