version: '3.4'

services:
  soot-java8:
    container_name: mysoot-java8
    image: soot-java8
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
        - ./app:/usr/app
    ports:
      - 3001:3000

    command: tail -f /dev/null # keep open container 

